"""
Constants will be here
"""

# Product types

RESUME_TYPE = 'RESUME'
COVER_LETTER_TYPE = 'COVER_LETTER'
PITCH_TYPE = 'PITCH'
SERVICE_TYPE = 'SERVICE'
VIDEO_TYPE = 'VIDEO'
ADVICE_TYPE = 'ADVICE'
PODCAST_TYPE = 'PODCAST'
BOOK_TYPE = 'BOOK'
PRODUCT_TYPES = [
    (RESUME_TYPE, 'RESUME'),
    (COVER_LETTER_TYPE, 'COVER_LETTER'),
    (PITCH_TYPE, 'PITCH'),
    (SERVICE_TYPE, 'SERVICE'),
    (VIDEO_TYPE, 'VIDEO'),
    (ADVICE_TYPE, 'ADVICE'),
    (PODCAST_TYPE, 'PODCAST'),
    (BOOK_TYPE, 'BOOK'),
]

DEFAULT_PRODUCT_TYPE = RESUME_TYPE
